import type { ProvinceData, CityData } from "./type";

export const provinceData: ProvinceData = {
  "110000": {
    pinyin: "beijing",
    pinyinShort: "bj",
    name: "北京市",
  },
  "120000": {
    pinyin: "tianjin",
    pinyinShort: "tj",
    name: "天津市",
  },
  "130000": {
    pinyin: "hebei",
    pinyinShort: "hb",
    name: "河北省",
  },
  "140000": {
    pinyin: "shanxi",
    pinyinShort: "sx",
    name: "山西省",
  },
  "150000": {
    pinyin: "neimenggu",
    pinyinShort: "nmg",
    name: "内蒙古自治区",
  },
  "210000": {
    pinyin: "liaoning",
    pinyinShort: "ln",
    name: "辽宁省",
  },
  "220000": {
    pinyin: "jilin",
    pinyinShort: "jl",
    name: "吉林省",
  },
  "230000": {
    pinyin: "heilongjiang",
    pinyinShort: "hlj",
    name: "黑龙江省",
  },
  "310000": {
    pinyin: "shanghai",
    pinyinShort: "sh",
    name: "上海市",
  },
  "320000": {
    pinyin: "jiangsu",
    pinyinShort: "js",
    name: "江苏省",
  },
  "330000": {
    pinyin: "zhejiang",
    pinyinShort: "zj",
    name: "浙江省",
  },
  "340000": {
    pinyin: "anhui",
    pinyinShort: "ah",
    name: "安徽省",
  },
  "350000": {
    pinyin: "fujian",
    pinyinShort: "fj",
    name: "福建省",
  },
  "360000": {
    pinyin: "jiangxi",
    pinyinShort: "jx",
    name: "江西省",
  },
  "370000": {
    pinyin: "shandong",
    pinyinShort: "sd",
    name: "山东省",
  },
  "410000": {
    pinyin: "henan",
    pinyinShort: "hn",
    name: "河南省",
  },
  "420000": {
    pinyin: "hubei",
    pinyinShort: "hb",
    name: "湖北省",
  },
  "430000": {
    pinyin: "hunan",
    pinyinShort: "hn",
    name: "湖南省",
  },
  "440000": {
    pinyin: "guangdong",
    pinyinShort: "gd",
    name: "广东省",
  },
  "450000": {
    pinyin: "guangxi",
    pinyinShort: "gx",
    name: "广西壮族自治区",
  },
  "460000": {
    pinyin: "hainan",
    pinyinShort: "hn",
    name: "海南省",
  },
  "500000": {
    pinyin: "chongqing",
    pinyinShort: "cq",
    name: "重庆市",
  },
  "510000": {
    pinyin: "sichuan",
    pinyinShort: "sc",
    name: "四川省",
  },
  "520000": {
    pinyin: "guizhou",
    pinyinShort: "gz",
    name: "贵州省",
  },
  "530000": {
    pinyin: "yunnan",
    pinyinShort: "yn",
    name: "云南省",
  },
  "540000": {
    pinyin: "xizang",
    pinyinShort: "xz",
    name: "西藏自治区",
  },
  "610000": {
    pinyin: "shanxi",
    pinyinShort: "sx",
    name: "陕西省",
  },
  "620000": {
    pinyin: "gansu",
    pinyinShort: "gs",
    name: "甘肃省",
  },
  "630000": {
    pinyin: "qinghai",
    pinyinShort: "qh",
    name: "青海省",
  },
  "640000": {
    pinyin: "ningxia",
    pinyinShort: "nx",
    name: "宁夏回族自治区",
  },
  "650000": {
    pinyin: "xinjiang",
    pinyinShort: "xj",
    name: "新疆维吾尔自治区",
  },
  "710000": {
    pinyin: "taiwan",
    pinyinShort: "tw",
    name: "台湾省",
  },
  "810000": {
    pinyin: "xianggang",
    pinyinShort: "xg",
    name: "香港",
  },
  "820000": {
    pinyin: "aomen",
    pinyinShort: "am",
    name: "澳门",
  },
};

export const cityData: CityData = {
  A: [
    {
      pinyin: "abazangzuqiangzuzizhizhou",
      pinyinShort: "abzzqzzzz",
      name: "阿坝藏族羌族自治州",
      code: "513200",
      pcode: "510000",
    },
    {
      pinyin: "akesudiqu",
      pinyinShort: "aksdq",
      name: "阿克苏地区",
      code: "652900",
      pcode: "650000",
    },
    {
      pinyin: "alaer",
      pinyinShort: "ale",
      name: "阿拉尔市",
      code: "659002",
      pcode: "650000",
    },
    {
      pinyin: "alashanmeng",
      pinyinShort: "alsm",
      name: "阿拉善盟",
      code: "152900",
      pcode: "150000",
    },
    {
      pinyin: "aletaidiqu",
      pinyinShort: "altdq",
      name: "阿勒泰地区",
      code: "654300",
      pcode: "650000",
    },
    {
      pinyin: "alidiqu",
      pinyinShort: "aldq",
      name: "阿里地区",
      code: "542500",
      pcode: "540000",
    },
    {
      pinyin: "ankang",
      pinyinShort: "ak",
      name: "安康市",
      code: "610900",
      pcode: "610000",
    },
    {
      pinyin: "anqing",
      pinyinShort: "aq",
      name: "安庆市",
      code: "340800",
      pcode: "340000",
    },
    {
      pinyin: "anshan",
      pinyinShort: "as",
      name: "鞍山市",
      code: "210300",
      pcode: "210000",
    },
    {
      pinyin: "anshun",
      pinyinShort: "as",
      name: "安顺市",
      code: "520400",
      pcode: "520000",
    },
    {
      pinyin: "anyang",
      pinyinShort: "ay",
      name: "安阳市",
      code: "410500",
      pcode: "410000",
    },
    {
      pinyin: "aomen",
      pinyinShort: "am",
      name: "澳门",
      code: "820000",
      pcode: "820000",
    },
  ],
  B: [
    {
      pinyin: "baicheng",
      pinyinShort: "bc",
      name: "白城市",
      code: "220800",
      pcode: "220000",
    },
    {
      pinyin: "baise",
      pinyinShort: "bs",
      name: "百色市",
      code: "451000",
      pcode: "450000",
    },
    {
      pinyin: "baishalizuzizhixian",
      pinyinShort: "bslzzzx",
      name: "白沙黎族自治县",
      code: "469025",
      pcode: "460000",
    },
    {
      pinyin: "baishan",
      pinyinShort: "bs",
      name: "白山市",
      code: "220600",
      pcode: "220000",
    },
    {
      pinyin: "baiyang",
      pinyinShort: "by",
      name: "白杨市",
      code: "659012",
      pcode: "650000",
    },
    {
      pinyin: "baiyin",
      pinyinShort: "by",
      name: "白银市",
      code: "620400",
      pcode: "620000",
    },
    {
      pinyin: "baoding",
      pinyinShort: "bd",
      name: "保定市",
      code: "130600",
      pcode: "130000",
    },
    {
      pinyin: "baoji",
      pinyinShort: "bj",
      name: "宝鸡市",
      code: "610300",
      pcode: "610000",
    },
    {
      pinyin: "baoshan",
      pinyinShort: "bs",
      name: "保山市",
      code: "530500",
      pcode: "530000",
    },
    {
      pinyin: "baotinglizumiaozuzizhixian",
      pinyinShort: "btlzmzzzx",
      name: "保亭黎族苗族自治县",
      code: "469029",
      pcode: "460000",
    },
    {
      pinyin: "baotou",
      pinyinShort: "bt",
      name: "包头市",
      code: "150200",
      pcode: "150000",
    },
    {
      pinyin: "bayannaoer",
      pinyinShort: "byne",
      name: "巴彦淖尔市",
      code: "150800",
      pcode: "150000",
    },
    {
      pinyin: "bayinguolengmengguzizhizhou",
      pinyinShort: "byglmgzzz",
      name: "巴音郭楞蒙古自治州",
      code: "652800",
      pcode: "650000",
    },
    {
      pinyin: "bazhong",
      pinyinShort: "bz",
      name: "巴中市",
      code: "511900",
      pcode: "510000",
    },
    {
      pinyin: "beihai",
      pinyinShort: "bh",
      name: "北海市",
      code: "450500",
      pcode: "450000",
    },
    {
      pinyin: "beijing",
      pinyinShort: "bj",
      name: "北京市",
      code: "110100",
      pcode: "110000",
    },
    {
      pinyin: "beitun",
      pinyinShort: "bt",
      name: "北屯市",
      code: "659005",
      pcode: "650000",
    },
    {
      pinyin: "bengbu",
      pinyinShort: "bb",
      name: "蚌埠市",
      code: "340300",
      pcode: "340000",
    },
    {
      pinyin: "benxi",
      pinyinShort: "bx",
      name: "本溪市",
      code: "210500",
      pcode: "210000",
    },
    {
      pinyin: "bijie",
      pinyinShort: "bj",
      name: "毕节市",
      code: "520500",
      pcode: "520000",
    },
    {
      pinyin: "binzhou",
      pinyinShort: "bz",
      name: "滨州市",
      code: "371600",
      pcode: "370000",
    },
    {
      pinyin: "boertalamengguzizhizhou",
      pinyinShort: "betlmgzzz",
      name: "博尔塔拉蒙古自治州",
      code: "652700",
      pcode: "650000",
    },
    {
      pinyin: "bozhou",
      pinyinShort: "bz",
      name: "亳州市",
      code: "341600",
      pcode: "340000",
    },
  ],
  C: [
    {
      pinyin: "cangzhou",
      pinyinShort: "cz",
      name: "沧州市",
      code: "130900",
      pcode: "130000",
    },
    {
      pinyin: "changchun",
      pinyinShort: "cc",
      name: "长春市",
      code: "220100",
      pcode: "220000",
    },
    {
      pinyin: "changde",
      pinyinShort: "cd",
      name: "常德市",
      code: "430700",
      pcode: "430000",
    },
    {
      pinyin: "changdou",
      pinyinShort: "cd",
      name: "昌都市",
      code: "540300",
      pcode: "540000",
    },
    {
      pinyin: "changjianglizuzizhixian",
      pinyinShort: "cjlzzzx",
      name: "昌江黎族自治县",
      code: "469026",
      pcode: "460000",
    },
    {
      pinyin: "changjihuizuzizhizhou",
      pinyinShort: "cjhzzzz",
      name: "昌吉回族自治州",
      code: "652300",
      pcode: "650000",
    },
    {
      pinyin: "changsha",
      pinyinShort: "cs",
      name: "长沙市",
      code: "430100",
      pcode: "430000",
    },
    {
      pinyin: "changzhi",
      pinyinShort: "cz",
      name: "长治市",
      code: "140400",
      pcode: "140000",
    },
    {
      pinyin: "changzhou",
      pinyinShort: "cz",
      name: "常州市",
      code: "320400",
      pcode: "320000",
    },
    {
      pinyin: "chaoyang",
      pinyinShort: "cy",
      name: "朝阳市",
      code: "211300",
      pcode: "210000",
    },
    {
      pinyin: "chaozhou",
      pinyinShort: "cz",
      name: "潮州市",
      code: "445100",
      pcode: "440000",
    },
    {
      pinyin: "chengde",
      pinyinShort: "cd",
      name: "承德市",
      code: "130800",
      pcode: "130000",
    },
    {
      pinyin: "chengdu",
      pinyinShort: "cd",
      name: "成都市",
      code: "510100",
      pcode: "510000",
    },
    {
      pinyin: "chengmaixian",
      pinyinShort: "cmx",
      name: "澄迈县",
      code: "469023",
      pcode: "460000",
    },
    {
      pinyin: "chenzhou",
      pinyinShort: "cz",
      name: "郴州市",
      code: "431000",
      pcode: "430000",
    },
    {
      pinyin: "chifeng",
      pinyinShort: "cf",
      name: "赤峰市",
      code: "150400",
      pcode: "150000",
    },
    {
      pinyin: "chizhou",
      pinyinShort: "cz",
      name: "池州市",
      code: "341700",
      pcode: "340000",
    },
    {
      pinyin: "chongqing",
      pinyinShort: "cq",
      name: "重庆市",
      code: "500100",
      pcode: "500000",
    },
    {
      pinyin: "chongzuo",
      pinyinShort: "cz",
      name: "崇左市",
      code: "451400",
      pcode: "450000",
    },
    {
      pinyin: "chuxiongyizuzizhizhou",
      pinyinShort: "cxyzzzz",
      name: "楚雄彝族自治州",
      code: "532300",
      pcode: "530000",
    },
    {
      pinyin: "chuzhou",
      pinyinShort: "cz",
      name: "滁州市",
      code: "341100",
      pcode: "340000",
    },
  ],
  D: [
    {
      pinyin: "dalian",
      pinyinShort: "dl",
      name: "大连市",
      code: "210200",
      pcode: "210000",
    },
    {
      pinyin: "dalibaizuzizhizhou",
      pinyinShort: "dlbzzzz",
      name: "大理白族自治州",
      code: "532900",
      pcode: "530000",
    },
    {
      pinyin: "dandong",
      pinyinShort: "dd",
      name: "丹东市",
      code: "210600",
      pcode: "210000",
    },
    {
      pinyin: "danzhou",
      pinyinShort: "dz",
      name: "儋州市",
      code: "460400",
      pcode: "460000",
    },
    {
      pinyin: "daqing",
      pinyinShort: "dq",
      name: "大庆市",
      code: "230600",
      pcode: "230000",
    },
    {
      pinyin: "datong",
      pinyinShort: "dt",
      name: "大同市",
      code: "140200",
      pcode: "140000",
    },
    {
      pinyin: "daxinganlingdiqu",
      pinyinShort: "dxaldq",
      name: "大兴安岭地区",
      code: "232700",
      pcode: "230000",
    },
    {
      pinyin: "dazhou",
      pinyinShort: "dz",
      name: "达州市",
      code: "511700",
      pcode: "510000",
    },
    {
      pinyin: "dehongdaizujingpozuzizhizhou",
      pinyinShort: "dhdzjpzzzz",
      name: "德宏傣族景颇族自治州",
      code: "533100",
      pcode: "530000",
    },
    {
      pinyin: "deyang",
      pinyinShort: "dy",
      name: "德阳市",
      code: "510600",
      pcode: "510000",
    },
    {
      pinyin: "dezhou",
      pinyinShort: "dz",
      name: "德州市",
      code: "371400",
      pcode: "370000",
    },
    {
      pinyin: "dinganxian",
      pinyinShort: "dax",
      name: "定安县",
      code: "469021",
      pcode: "460000",
    },
    {
      pinyin: "dingxi",
      pinyinShort: "dx",
      name: "定西市",
      code: "621100",
      pcode: "620000",
    },
    {
      pinyin: "diqingzangzuzizhizhou",
      pinyinShort: "dqzzzzz",
      name: "迪庆藏族自治州",
      code: "533400",
      pcode: "530000",
    },
    {
      pinyin: "dongfang",
      pinyinShort: "df",
      name: "东方市",
      code: "469007",
      pcode: "460000",
    },
    {
      pinyin: "dongguan",
      pinyinShort: "dg",
      name: "东莞市",
      code: "441900",
      pcode: "440000",
    },
    {
      pinyin: "dongying",
      pinyinShort: "dy",
      name: "东营市",
      code: "370500",
      pcode: "370000",
    },
  ],
  E: [
    {
      pinyin: "eerduosi",
      pinyinShort: "eeds",
      name: "鄂尔多斯市",
      code: "150600",
      pcode: "150000",
    },
    {
      pinyin: "enshitujiazumiaozuzizhizhou",
      pinyinShort: "estjzmzzzz",
      name: "恩施土家族苗族自治州",
      code: "422800",
      pcode: "420000",
    },
    {
      pinyin: "ezhou",
      pinyinShort: "ez",
      name: "鄂州市",
      code: "420700",
      pcode: "420000",
    },
  ],
  F: [
    {
      pinyin: "fangchenggang",
      pinyinShort: "fcg",
      name: "防城港市",
      code: "450600",
      pcode: "450000",
    },
    {
      pinyin: "foshan",
      pinyinShort: "fs",
      name: "佛山市",
      code: "440600",
      pcode: "440000",
    },
    {
      pinyin: "fushun",
      pinyinShort: "fs",
      name: "抚顺市",
      code: "210400",
      pcode: "210000",
    },
    {
      pinyin: "fuxin",
      pinyinShort: "fx",
      name: "阜新市",
      code: "210900",
      pcode: "210000",
    },
    {
      pinyin: "fuyang",
      pinyinShort: "fy",
      name: "阜阳市",
      code: "341200",
      pcode: "340000",
    },
    {
      pinyin: "fuzhou",
      pinyinShort: "fz",
      name: "抚州市",
      code: "361000",
      pcode: "360000",
    },
    {
      pinyin: "fuzhou",
      pinyinShort: "fz",
      name: "福州市",
      code: "350100",
      pcode: "350000",
    },
  ],
  G: [
    {
      pinyin: "gannanzangzuzizhizhou",
      pinyinShort: "gnzzzzz",
      name: "甘南藏族自治州",
      code: "623000",
      pcode: "620000",
    },
    {
      pinyin: "ganzhou",
      pinyinShort: "gz",
      name: "赣州市",
      code: "360700",
      pcode: "360000",
    },
    {
      pinyin: "ganzizangzuzizhizhou",
      pinyinShort: "gzzzzzz",
      name: "甘孜藏族自治州",
      code: "513300",
      pcode: "510000",
    },
    {
      pinyin: "gaoxiong",
      pinyinShort: "gx",
      name: "高雄市",
      code: "710200",
      pcode: "710000",
    },
    {
      pinyin: "guangan",
      pinyinShort: "ga",
      name: "广安市",
      code: "511600",
      pcode: "510000",
    },
    {
      pinyin: "guangyuan",
      pinyinShort: "gy",
      name: "广元市",
      code: "510800",
      pcode: "510000",
    },
    {
      pinyin: "guangzhou",
      pinyinShort: "gz",
      name: "广州市",
      code: "440100",
      pcode: "440000",
    },
    {
      pinyin: "guigang",
      pinyinShort: "gg",
      name: "贵港市",
      code: "450800",
      pcode: "450000",
    },
    {
      pinyin: "guilin",
      pinyinShort: "gl",
      name: "桂林市",
      code: "450300",
      pcode: "450000",
    },
    {
      pinyin: "guiyang",
      pinyinShort: "gy",
      name: "贵阳市",
      code: "520100",
      pcode: "520000",
    },
    {
      pinyin: "guoluozangzuzizhizhou",
      pinyinShort: "glzzzzz",
      name: "果洛藏族自治州",
      code: "632600",
      pcode: "630000",
    },
    {
      pinyin: "guyuan",
      pinyinShort: "gy",
      name: "固原市",
      code: "640400",
      pcode: "640000",
    },
  ],
  H: [
    {
      pinyin: "haerbin",
      pinyinShort: "heb",
      name: "哈尔滨市",
      code: "230100",
      pcode: "230000",
    },
    {
      pinyin: "haibeizangzuzizhizhou",
      pinyinShort: "hbzzzzz",
      name: "海北藏族自治州",
      code: "632200",
      pcode: "630000",
    },
    {
      pinyin: "haidong",
      pinyinShort: "hd",
      name: "海东市",
      code: "630200",
      pcode: "630000",
    },
    {
      pinyin: "haikou",
      pinyinShort: "hk",
      name: "海口市",
      code: "460100",
      pcode: "460000",
    },
    {
      pinyin: "hainanzangzuzizhizhou",
      pinyinShort: "hnzzzzz",
      name: "海南藏族自治州",
      code: "632500",
      pcode: "630000",
    },
    {
      pinyin: "haiximengguzuzangzuzizhizhou",
      pinyinShort: "hxmgzzzzzz",
      name: "海西蒙古族藏族自治州",
      code: "632800",
      pcode: "630000",
    },
    {
      pinyin: "hami",
      pinyinShort: "hm",
      name: "哈密市",
      code: "650500",
      pcode: "650000",
    },
    {
      pinyin: "handan",
      pinyinShort: "hd",
      name: "邯郸市",
      code: "130400",
      pcode: "130000",
    },
    {
      pinyin: "hangzhou",
      pinyinShort: "hz",
      name: "杭州市",
      code: "330100",
      pcode: "330000",
    },
    {
      pinyin: "hanzhong",
      pinyinShort: "hz",
      name: "汉中市",
      code: "610700",
      pcode: "610000",
    },
    {
      pinyin: "hebi",
      pinyinShort: "hb",
      name: "鹤壁市",
      code: "410600",
      pcode: "410000",
    },
    {
      pinyin: "hechi",
      pinyinShort: "hc",
      name: "河池市",
      code: "451200",
      pcode: "450000",
    },
    {
      pinyin: "hefei",
      pinyinShort: "hf",
      name: "合肥市",
      code: "340100",
      pcode: "340000",
    },
    {
      pinyin: "hegang",
      pinyinShort: "hg",
      name: "鹤岗市",
      code: "230400",
      pcode: "230000",
    },
    {
      pinyin: "heihe",
      pinyinShort: "hh",
      name: "黑河市",
      code: "231100",
      pcode: "230000",
    },
    {
      pinyin: "hengshui",
      pinyinShort: "hs",
      name: "衡水市",
      code: "131100",
      pcode: "130000",
    },
    {
      pinyin: "hengyang",
      pinyinShort: "hy",
      name: "衡阳市",
      code: "430400",
      pcode: "430000",
    },
    {
      pinyin: "hetiandiqu",
      pinyinShort: "htdq",
      name: "和田地区",
      code: "653200",
      pcode: "650000",
    },
    {
      pinyin: "heyuan",
      pinyinShort: "hy",
      name: "河源市",
      code: "441600",
      pcode: "440000",
    },
    {
      pinyin: "heze",
      pinyinShort: "hz",
      name: "菏泽市",
      code: "371700",
      pcode: "370000",
    },
    {
      pinyin: "hezhou",
      pinyinShort: "hz",
      name: "贺州市",
      code: "451100",
      pcode: "450000",
    },
    {
      pinyin: "honghehanizuyizuzizhizhou",
      pinyinShort: "hhhnzyzzzz",
      name: "红河哈尼族彝族自治州",
      code: "532500",
      pcode: "530000",
    },
    {
      pinyin: "huaian",
      pinyinShort: "ha",
      name: "淮安市",
      code: "320800",
      pcode: "320000",
    },
    {
      pinyin: "huaibei",
      pinyinShort: "hb",
      name: "淮北市",
      code: "340600",
      pcode: "340000",
    },
    {
      pinyin: "huaihua",
      pinyinShort: "hh",
      name: "怀化市",
      code: "431200",
      pcode: "430000",
    },
    {
      pinyin: "huainan",
      pinyinShort: "hn",
      name: "淮南市",
      code: "340400",
      pcode: "340000",
    },
    {
      pinyin: "hualianxian",
      pinyinShort: "hlx",
      name: "花莲县",
      code: "719013",
      pcode: "710000",
    },
    {
      pinyin: "huanggang",
      pinyinShort: "hg",
      name: "黄冈市",
      code: "421100",
      pcode: "420000",
    },
    {
      pinyin: "huangnanzangzuzizhizhou",
      pinyinShort: "hnzzzzz",
      name: "黄南藏族自治州",
      code: "632300",
      pcode: "630000",
    },
    {
      pinyin: "huangshan",
      pinyinShort: "hs",
      name: "黄山市",
      code: "341000",
      pcode: "340000",
    },
    {
      pinyin: "huangshi",
      pinyinShort: "hs",
      name: "黄石市",
      code: "420200",
      pcode: "420000",
    },
    {
      pinyin: "huhehaote",
      pinyinShort: "hhht",
      name: "呼和浩特市",
      code: "150100",
      pcode: "150000",
    },
    {
      pinyin: "huizhou",
      pinyinShort: "hz",
      name: "惠州市",
      code: "441300",
      pcode: "440000",
    },
    {
      pinyin: "huludao",
      pinyinShort: "hld",
      name: "葫芦岛市",
      code: "211400",
      pcode: "210000",
    },
    {
      pinyin: "hulunbeier",
      pinyinShort: "hlbe",
      name: "呼伦贝尔市",
      code: "150700",
      pcode: "150000",
    },
    {
      pinyin: "huyanghe",
      pinyinShort: "hyh",
      name: "胡杨河市",
      code: "659010",
      pcode: "650000",
    },
    {
      pinyin: "huzhou",
      pinyinShort: "hz",
      name: "湖州市",
      code: "330500",
      pcode: "330000",
    },
  ],
  J: [
    {
      pinyin: "jiamusi",
      pinyinShort: "jms",
      name: "佳木斯市",
      code: "230800",
      pcode: "230000",
    },
    {
      pinyin: "jian",
      pinyinShort: "ja",
      name: "吉安市",
      code: "360800",
      pcode: "360000",
    },
    {
      pinyin: "jiangmen",
      pinyinShort: "jm",
      name: "江门市",
      code: "440700",
      pcode: "440000",
    },
    {
      pinyin: "jiaozuo",
      pinyinShort: "jz",
      name: "焦作市",
      code: "410800",
      pcode: "410000",
    },
    {
      pinyin: "jiaxing",
      pinyinShort: "jx",
      name: "嘉兴市",
      code: "330400",
      pcode: "330000",
    },
    {
      pinyin: "jiayi",
      pinyinShort: "jy",
      name: "嘉义市",
      code: "719003",
      pcode: "710000",
    },
    {
      pinyin: "jiayixian",
      pinyinShort: "jyx",
      name: "嘉义县",
      code: "719010",
      pcode: "710000",
    },
    {
      pinyin: "jiayuguan",
      pinyinShort: "jyg",
      name: "嘉峪关市",
      code: "620200",
      pcode: "620000",
    },
    {
      pinyin: "jieyang",
      pinyinShort: "jy",
      name: "揭阳市",
      code: "445200",
      pcode: "440000",
    },
    {
      pinyin: "jilin",
      pinyinShort: "jl",
      name: "吉林市",
      code: "220200",
      pcode: "220000",
    },
    {
      pinyin: "jilong",
      pinyinShort: "jl",
      name: "基隆市",
      code: "719001",
      pcode: "710000",
    },
    {
      pinyin: "jinan",
      pinyinShort: "jn",
      name: "济南市",
      code: "370100",
      pcode: "370000",
    },
    {
      pinyin: "jinchang",
      pinyinShort: "jc",
      name: "金昌市",
      code: "620300",
      pcode: "620000",
    },
    {
      pinyin: "jincheng",
      pinyinShort: "jc",
      name: "晋城市",
      code: "140500",
      pcode: "140000",
    },
    {
      pinyin: "jingdezhen",
      pinyinShort: "jdz",
      name: "景德镇市",
      code: "360200",
      pcode: "360000",
    },
    {
      pinyin: "jingmen",
      pinyinShort: "jm",
      name: "荆门市",
      code: "420800",
      pcode: "420000",
    },
    {
      pinyin: "jingzhou",
      pinyinShort: "jz",
      name: "荆州市",
      code: "421000",
      pcode: "420000",
    },
    {
      pinyin: "jinhua",
      pinyinShort: "jh",
      name: "金华市",
      code: "330700",
      pcode: "330000",
    },
    {
      pinyin: "jining",
      pinyinShort: "jn",
      name: "济宁市",
      code: "370800",
      pcode: "370000",
    },
    {
      pinyin: "jinzhong",
      pinyinShort: "jz",
      name: "晋中市",
      code: "140700",
      pcode: "140000",
    },
    {
      pinyin: "jinzhou",
      pinyinShort: "jz",
      name: "锦州市",
      code: "210700",
      pcode: "210000",
    },
    {
      pinyin: "jiujiang",
      pinyinShort: "jj",
      name: "九江市",
      code: "360400",
      pcode: "360000",
    },
    {
      pinyin: "jiuquan",
      pinyinShort: "jq",
      name: "酒泉市",
      code: "620900",
      pcode: "620000",
    },
    {
      pinyin: "jixi",
      pinyinShort: "jx",
      name: "鸡西市",
      code: "230300",
      pcode: "230000",
    },
    {
      pinyin: "jiyuan",
      pinyinShort: "jy",
      name: "济源市",
      code: "419001",
      pcode: "410000",
    },
  ],
  K: [
    {
      pinyin: "kaifeng",
      pinyinShort: "kf",
      name: "开封市",
      code: "410200",
      pcode: "410000",
    },
    {
      pinyin: "kashendiqu",
      pinyinShort: "ksdq",
      name: "喀什地区",
      code: "653100",
      pcode: "650000",
    },
    {
      pinyin: "kekedala",
      pinyinShort: "kkdl",
      name: "可克达拉市",
      code: "659008",
      pcode: "650000",
    },
    {
      pinyin: "kelamayi",
      pinyinShort: "klmy",
      name: "克拉玛依市",
      code: "650200",
      pcode: "650000",
    },
    {
      pinyin: "kezilesukeerkezizizhizhou",
      pinyinShort: "kzlskekzzzz",
      name: "克孜勒苏柯尔克孜自治州",
      code: "653000",
      pcode: "650000",
    },
    {
      pinyin: "kunming",
      pinyinShort: "km",
      name: "昆明市",
      code: "530100",
      pcode: "530000",
    },
    {
      pinyin: "kunyu",
      pinyinShort: "ky",
      name: "昆玉市",
      code: "659009",
      pcode: "650000",
    },
  ],
  L: [
    {
      pinyin: "laibin",
      pinyinShort: "lb",
      name: "来宾市",
      code: "451300",
      pcode: "450000",
    },
    {
      pinyin: "langfang",
      pinyinShort: "lf",
      name: "廊坊市",
      code: "131000",
      pcode: "130000",
    },
    {
      pinyin: "lanzhou",
      pinyinShort: "lz",
      name: "兰州市",
      code: "620100",
      pcode: "620000",
    },
    {
      pinyin: "lasa",
      pinyinShort: "ls",
      name: "拉萨市",
      code: "540100",
      pcode: "540000",
    },
    {
      pinyin: "ledonglizuzizhixian",
      pinyinShort: "ldlzzzx",
      name: "乐东黎族自治县",
      code: "469027",
      pcode: "460000",
    },
    {
      pinyin: "leshan",
      pinyinShort: "ls",
      name: "乐山市",
      code: "511100",
      pcode: "510000",
    },
    {
      pinyin: "liangshanyizuzizhizhou",
      pinyinShort: "lsyzzzz",
      name: "凉山彝族自治州",
      code: "513400",
      pcode: "510000",
    },
    {
      pinyin: "lianyungang",
      pinyinShort: "lyg",
      name: "连云港市",
      code: "320700",
      pcode: "320000",
    },
    {
      pinyin: "liaocheng",
      pinyinShort: "lc",
      name: "聊城市",
      code: "371500",
      pcode: "370000",
    },
    {
      pinyin: "liaoyang",
      pinyinShort: "ly",
      name: "辽阳市",
      code: "211000",
      pcode: "210000",
    },
    {
      pinyin: "liaoyuan",
      pinyinShort: "ly",
      name: "辽源市",
      code: "220400",
      pcode: "220000",
    },
    {
      pinyin: "lijiang",
      pinyinShort: "lj",
      name: "丽江市",
      code: "530700",
      pcode: "530000",
    },
    {
      pinyin: "lincang",
      pinyinShort: "lc",
      name: "临沧市",
      code: "530900",
      pcode: "530000",
    },
    {
      pinyin: "linfen",
      pinyinShort: "lf",
      name: "临汾市",
      code: "141000",
      pcode: "140000",
    },
    {
      pinyin: "lingaoxian",
      pinyinShort: "lgx",
      name: "临高县",
      code: "469024",
      pcode: "460000",
    },
    {
      pinyin: "lingshuilizuzizhixian",
      pinyinShort: "lslzzzx",
      name: "陵水黎族自治县",
      code: "469028",
      pcode: "460000",
    },
    {
      pinyin: "linxiahuizuzizhizhou",
      pinyinShort: "lxhzzzz",
      name: "临夏回族自治州",
      code: "622900",
      pcode: "620000",
    },
    {
      pinyin: "linyi",
      pinyinShort: "ly",
      name: "临沂市",
      code: "371300",
      pcode: "370000",
    },
    {
      pinyin: "linzhi",
      pinyinShort: "lz",
      name: "林芝市",
      code: "540400",
      pcode: "540000",
    },
    {
      pinyin: "lishui",
      pinyinShort: "ls",
      name: "丽水市",
      code: "331100",
      pcode: "330000",
    },
    {
      pinyin: "liupanshui",
      pinyinShort: "lps",
      name: "六盘水市",
      code: "520200",
      pcode: "520000",
    },
    {
      pinyin: "liuzhou",
      pinyinShort: "lz",
      name: "柳州市",
      code: "450200",
      pcode: "450000",
    },
    {
      pinyin: "longnan",
      pinyinShort: "ln",
      name: "陇南市",
      code: "621200",
      pcode: "620000",
    },
    {
      pinyin: "longyan",
      pinyinShort: "ly",
      name: "龙岩市",
      code: "350800",
      pcode: "350000",
    },
    {
      pinyin: "loudi",
      pinyinShort: "ld",
      name: "娄底市",
      code: "431300",
      pcode: "430000",
    },
    {
      pinyin: "luan",
      pinyinShort: "la",
      name: "六安市",
      code: "341500",
      pcode: "340000",
    },
    {
      pinyin: "lüliang",
      pinyinShort: "ll",
      name: "吕梁市",
      code: "141100",
      pcode: "140000",
    },
    {
      pinyin: "luohe",
      pinyinShort: "lh",
      name: "漯河市",
      code: "411100",
      pcode: "410000",
    },
    {
      pinyin: "luoyang",
      pinyinShort: "ly",
      name: "洛阳市",
      code: "410300",
      pcode: "410000",
    },
    {
      pinyin: "luzhou",
      pinyinShort: "lz",
      name: "泸州市",
      code: "510500",
      pcode: "510000",
    },
  ],
  M: [
    {
      pinyin: "maanshan",
      pinyinShort: "mas",
      name: "马鞍山市",
      code: "340500",
      pcode: "340000",
    },
    {
      pinyin: "maoming",
      pinyinShort: "mm",
      name: "茂名市",
      code: "440900",
      pcode: "440000",
    },
    {
      pinyin: "meishan",
      pinyinShort: "ms",
      name: "眉山市",
      code: "511400",
      pcode: "510000",
    },
    {
      pinyin: "meizhou",
      pinyinShort: "mz",
      name: "梅州市",
      code: "441400",
      pcode: "440000",
    },
    {
      pinyin: "mianyang",
      pinyinShort: "my",
      name: "绵阳市",
      code: "510700",
      pcode: "510000",
    },
    {
      pinyin: "miaolixian",
      pinyinShort: "mlx",
      name: "苗栗县",
      code: "719006",
      pcode: "710000",
    },
    {
      pinyin: "mudanjiang",
      pinyinShort: "mdj",
      name: "牡丹江市",
      code: "231000",
      pcode: "230000",
    },
  ],
  N: [
    {
      pinyin: "nanchang",
      pinyinShort: "nc",
      name: "南昌市",
      code: "360100",
      pcode: "360000",
    },
    {
      pinyin: "nanchong",
      pinyinShort: "nc",
      name: "南充市",
      code: "511300",
      pcode: "510000",
    },
    {
      pinyin: "nanjing",
      pinyinShort: "nj",
      name: "南京市",
      code: "320100",
      pcode: "320000",
    },
    {
      pinyin: "nanning",
      pinyinShort: "nn",
      name: "南宁市",
      code: "450100",
      pcode: "450000",
    },
    {
      pinyin: "nanping",
      pinyinShort: "np",
      name: "南平市",
      code: "350700",
      pcode: "350000",
    },
    {
      pinyin: "nantong",
      pinyinShort: "nt",
      name: "南通市",
      code: "320600",
      pcode: "320000",
    },
    {
      pinyin: "nantouxian",
      pinyinShort: "ntx",
      name: "南投县",
      code: "719009",
      pcode: "710000",
    },
    {
      pinyin: "nanyang",
      pinyinShort: "ny",
      name: "南阳市",
      code: "411300",
      pcode: "410000",
    },
    {
      pinyin: "naqu",
      pinyinShort: "nq",
      name: "那曲市",
      code: "540600",
      pcode: "540000",
    },
    {
      pinyin: "neijiang",
      pinyinShort: "nj",
      name: "内江市",
      code: "511000",
      pcode: "510000",
    },
    {
      pinyin: "ningbo",
      pinyinShort: "nb",
      name: "宁波市",
      code: "330200",
      pcode: "330000",
    },
    {
      pinyin: "ningde",
      pinyinShort: "nd",
      name: "宁德市",
      code: "350900",
      pcode: "350000",
    },
    {
      pinyin: "nujianglisuzuzizhizhou",
      pinyinShort: "njlszzzz",
      name: "怒江傈僳族自治州",
      code: "533300",
      pcode: "530000",
    },
  ],
  P: [
    {
      pinyin: "panjin",
      pinyinShort: "pj",
      name: "盘锦市",
      code: "211100",
      pcode: "210000",
    },
    {
      pinyin: "panzhihua",
      pinyinShort: "pzh",
      name: "攀枝花市",
      code: "510400",
      pcode: "510000",
    },
    {
      pinyin: "penghuxian",
      pinyinShort: "phx",
      name: "澎湖县",
      code: "719014",
      pcode: "710000",
    },
    {
      pinyin: "pingdingshan",
      pinyinShort: "pds",
      name: "平顶山市",
      code: "410400",
      pcode: "410000",
    },
    {
      pinyin: "pingdongxian",
      pinyinShort: "pdx",
      name: "屏东县",
      code: "719011",
      pcode: "710000",
    },
    {
      pinyin: "pingliang",
      pinyinShort: "pl",
      name: "平凉市",
      code: "620800",
      pcode: "620000",
    },
    {
      pinyin: "pingxiang",
      pinyinShort: "px",
      name: "萍乡市",
      code: "360300",
      pcode: "360000",
    },
    {
      pinyin: "puer",
      pinyinShort: "pe",
      name: "普洱市",
      code: "530800",
      pcode: "530000",
    },
    {
      pinyin: "putian",
      pinyinShort: "pt",
      name: "莆田市",
      code: "350300",
      pcode: "350000",
    },
    {
      pinyin: "puyang",
      pinyinShort: "py",
      name: "濮阳市",
      code: "410900",
      pcode: "410000",
    },
  ],
  Q: [
    {
      pinyin: "qiandongnanmiaozudongzuzizhizhou",
      pinyinShort: "qdnmzdzzzz",
      name: "黔东南苗族侗族自治州",
      code: "522600",
      pcode: "520000",
    },
    {
      pinyin: "qianjiang",
      pinyinShort: "qj",
      name: "潜江市",
      code: "429005",
      pcode: "420000",
    },
    {
      pinyin: "qiannanbuyizumiaozuzizhizhou",
      pinyinShort: "qnbyzmzzzz",
      name: "黔南布依族苗族自治州",
      code: "522700",
      pcode: "520000",
    },
    {
      pinyin: "qianxinanbuyizumiaozuzizhizhou",
      pinyinShort: "qxnbyzmzzzz",
      name: "黔西南布依族苗族自治州",
      code: "522300",
      pcode: "520000",
    },
    {
      pinyin: "qingdao",
      pinyinShort: "qd",
      name: "青岛市",
      code: "370200",
      pcode: "370000",
    },
    {
      pinyin: "qingyang",
      pinyinShort: "qy",
      name: "庆阳市",
      code: "621000",
      pcode: "620000",
    },
    {
      pinyin: "qingyuan",
      pinyinShort: "qy",
      name: "清远市",
      code: "441800",
      pcode: "440000",
    },
    {
      pinyin: "qinhuangdao",
      pinyinShort: "qhd",
      name: "秦皇岛市",
      code: "130300",
      pcode: "130000",
    },
    {
      pinyin: "qinzhou",
      pinyinShort: "qz",
      name: "钦州市",
      code: "450700",
      pcode: "450000",
    },
    {
      pinyin: "qionghai",
      pinyinShort: "qh",
      name: "琼海市",
      code: "469002",
      pcode: "460000",
    },
    {
      pinyin: "qiongzhonglizumiaozuzizhixian",
      pinyinShort: "qzlzmzzzx",
      name: "琼中黎族苗族自治县",
      code: "469030",
      pcode: "460000",
    },
    {
      pinyin: "qiqihaer",
      pinyinShort: "qqhe",
      name: "齐齐哈尔市",
      code: "230200",
      pcode: "230000",
    },
    {
      pinyin: "qitaihe",
      pinyinShort: "qth",
      name: "七台河市",
      code: "230900",
      pcode: "230000",
    },
    {
      pinyin: "quanzhou",
      pinyinShort: "qz",
      name: "泉州市",
      code: "350500",
      pcode: "350000",
    },
    {
      pinyin: "qujing",
      pinyinShort: "qj",
      name: "曲靖市",
      code: "530300",
      pcode: "530000",
    },
    {
      pinyin: "quzhou",
      pinyinShort: "qz",
      name: "衢州市",
      code: "330800",
      pcode: "330000",
    },
  ],
  R: [
    {
      pinyin: "rikaze",
      pinyinShort: "rkz",
      name: "日喀则市",
      code: "540200",
      pcode: "540000",
    },
    {
      pinyin: "rizhao",
      pinyinShort: "rz",
      name: "日照市",
      code: "371100",
      pcode: "370000",
    },
  ],
  S: [
    {
      pinyin: "sanmenxia",
      pinyinShort: "smx",
      name: "三门峡市",
      code: "411200",
      pcode: "410000",
    },
    {
      pinyin: "sanming",
      pinyinShort: "sm",
      name: "三明市",
      code: "350400",
      pcode: "350000",
    },
    {
      pinyin: "sansha",
      pinyinShort: "ss",
      name: "三沙市",
      code: "460300",
      pcode: "460000",
    },
    {
      pinyin: "sanya",
      pinyinShort: "sy",
      name: "三亚市",
      code: "460200",
      pcode: "460000",
    },
    {
      pinyin: "shanghai",
      pinyinShort: "sh",
      name: "上海市",
      code: "310100",
      pcode: "310000",
    },
    {
      pinyin: "shangluo",
      pinyinShort: "sl",
      name: "商洛市",
      code: "611000",
      pcode: "610000",
    },
    {
      pinyin: "shangqiu",
      pinyinShort: "sq",
      name: "商丘市",
      code: "411400",
      pcode: "410000",
    },
    {
      pinyin: "shangrao",
      pinyinShort: "sr",
      name: "上饶市",
      code: "361100",
      pcode: "360000",
    },
    {
      pinyin: "shannan",
      pinyinShort: "sn",
      name: "山南市",
      code: "540500",
      pcode: "540000",
    },
    {
      pinyin: "shantou",
      pinyinShort: "st",
      name: "汕头市",
      code: "440500",
      pcode: "440000",
    },
    {
      pinyin: "shanwei",
      pinyinShort: "sw",
      name: "汕尾市",
      code: "441500",
      pcode: "440000",
    },
    {
      pinyin: "shaoguan",
      pinyinShort: "sg",
      name: "韶关市",
      code: "440200",
      pcode: "440000",
    },
    {
      pinyin: "shaoxing",
      pinyinShort: "sx",
      name: "绍兴市",
      code: "330600",
      pcode: "330000",
    },
    {
      pinyin: "shaoyang",
      pinyinShort: "sy",
      name: "邵阳市",
      code: "430500",
      pcode: "430000",
    },
    {
      pinyin: "shennongjialinqu",
      pinyinShort: "snjlq",
      name: "神农架林区",
      code: "429021",
      pcode: "420000",
    },
    {
      pinyin: "shenyang",
      pinyinShort: "sy",
      name: "沈阳市",
      code: "210100",
      pcode: "210000",
    },
    {
      pinyin: "shenzhen",
      pinyinShort: "sz",
      name: "深圳市",
      code: "440300",
      pcode: "440000",
    },
    {
      pinyin: "shihezi",
      pinyinShort: "shz",
      name: "石河子市",
      code: "659001",
      pcode: "650000",
    },
    {
      pinyin: "shijiazhuang",
      pinyinShort: "sjz",
      name: "石家庄市",
      code: "130100",
      pcode: "130000",
    },
    {
      pinyin: "shiyan",
      pinyinShort: "sy",
      name: "十堰市",
      code: "420300",
      pcode: "420000",
    },
    {
      pinyin: "shizuishan",
      pinyinShort: "szs",
      name: "石嘴山市",
      code: "640200",
      pcode: "640000",
    },
    {
      pinyin: "shuanghe",
      pinyinShort: "sh",
      name: "双河市",
      code: "659007",
      pcode: "650000",
    },
    {
      pinyin: "shuangyashan",
      pinyinShort: "sys",
      name: "双鸭山市",
      code: "230500",
      pcode: "230000",
    },
    {
      pinyin: "shuozhou",
      pinyinShort: "sz",
      name: "朔州市",
      code: "140600",
      pcode: "140000",
    },
    {
      pinyin: "siping",
      pinyinShort: "sp",
      name: "四平市",
      code: "220300",
      pcode: "220000",
    },
    {
      pinyin: "songyuan",
      pinyinShort: "sy",
      name: "松原市",
      code: "220700",
      pcode: "220000",
    },
    {
      pinyin: "suihua",
      pinyinShort: "sh",
      name: "绥化市",
      code: "231200",
      pcode: "230000",
    },
    {
      pinyin: "suining",
      pinyinShort: "sn",
      name: "遂宁市",
      code: "510900",
      pcode: "510000",
    },
    {
      pinyin: "suizhou",
      pinyinShort: "sz",
      name: "随州市",
      code: "421300",
      pcode: "420000",
    },
    {
      pinyin: "suqian",
      pinyinShort: "sq",
      name: "宿迁市",
      code: "321300",
      pcode: "320000",
    },
    {
      pinyin: "suzhou",
      pinyinShort: "sz",
      name: "宿州市",
      code: "341300",
      pcode: "340000",
    },
    {
      pinyin: "suzhou",
      pinyinShort: "sz",
      name: "苏州市",
      code: "320500",
      pcode: "320000",
    },
  ],
  T: [
    {
      pinyin: "tachengdiqu",
      pinyinShort: "tcdq",
      name: "塔城地区",
      code: "654200",
      pcode: "650000",
    },
    {
      pinyin: "taian",
      pinyinShort: "ta",
      name: "泰安市",
      code: "370900",
      pcode: "370000",
    },
    {
      pinyin: "taibei",
      pinyinShort: "tb",
      name: "台北市",
      code: "710100",
      pcode: "710000",
    },
    {
      pinyin: "taidongxian",
      pinyinShort: "tdx",
      name: "台东县",
      code: "719012",
      pcode: "710000",
    },
    {
      pinyin: "tainan",
      pinyinShort: "tn",
      name: "台南市",
      code: "710500",
      pcode: "710000",
    },
    {
      pinyin: "taiyuan",
      pinyinShort: "ty",
      name: "太原市",
      code: "140100",
      pcode: "140000",
    },
    {
      pinyin: "taizhong",
      pinyinShort: "tz",
      name: "台中市",
      code: "710400",
      pcode: "710000",
    },
    {
      pinyin: "taizhou",
      pinyinShort: "tz",
      name: "台州市",
      code: "331000",
      pcode: "330000",
    },
    {
      pinyin: "taizhou",
      pinyinShort: "tz",
      name: "泰州市",
      code: "321200",
      pcode: "320000",
    },
    {
      pinyin: "tangshan",
      pinyinShort: "ts",
      name: "唐山市",
      code: "130200",
      pcode: "130000",
    },
    {
      pinyin: "taoyuan",
      pinyinShort: "ty",
      name: "桃园市",
      code: "710600",
      pcode: "710000",
    },
    {
      pinyin: "tianjin",
      pinyinShort: "tj",
      name: "天津市",
      code: "120100",
      pcode: "120000",
    },
    {
      pinyin: "tianmen",
      pinyinShort: "tm",
      name: "天门市",
      code: "429006",
      pcode: "420000",
    },
    {
      pinyin: "tianshui",
      pinyinShort: "ts",
      name: "天水市",
      code: "620500",
      pcode: "620000",
    },
    {
      pinyin: "tieling",
      pinyinShort: "tl",
      name: "铁岭市",
      code: "211200",
      pcode: "210000",
    },
    {
      pinyin: "tiemenguan",
      pinyinShort: "tmg",
      name: "铁门关市",
      code: "659006",
      pcode: "650000",
    },
    {
      pinyin: "tongchuan",
      pinyinShort: "tc",
      name: "铜川市",
      code: "610200",
      pcode: "610000",
    },
    {
      pinyin: "tonghua",
      pinyinShort: "th",
      name: "通化市",
      code: "220500",
      pcode: "220000",
    },
    {
      pinyin: "tongliao",
      pinyinShort: "tl",
      name: "通辽市",
      code: "150500",
      pcode: "150000",
    },
    {
      pinyin: "tongling",
      pinyinShort: "tl",
      name: "铜陵市",
      code: "340700",
      pcode: "340000",
    },
    {
      pinyin: "tongren",
      pinyinShort: "tr",
      name: "铜仁市",
      code: "520600",
      pcode: "520000",
    },
    {
      pinyin: "tulufan",
      pinyinShort: "tlf",
      name: "吐鲁番市",
      code: "650400",
      pcode: "650000",
    },
    {
      pinyin: "tumushuke",
      pinyinShort: "tmsk",
      name: "图木舒克市",
      code: "659003",
      pcode: "650000",
    },
    {
      pinyin: "tunchangxian",
      pinyinShort: "tcx",
      name: "屯昌县",
      code: "469022",
      pcode: "460000",
    },
  ],
  W: [
    {
      pinyin: "wanning",
      pinyinShort: "wn",
      name: "万宁市",
      code: "469006",
      pcode: "460000",
    },
    {
      pinyin: "weifang",
      pinyinShort: "wf",
      name: "潍坊市",
      code: "370700",
      pcode: "370000",
    },
    {
      pinyin: "weihai",
      pinyinShort: "wh",
      name: "威海市",
      code: "371000",
      pcode: "370000",
    },
    {
      pinyin: "weinan",
      pinyinShort: "wn",
      name: "渭南市",
      code: "610500",
      pcode: "610000",
    },
    {
      pinyin: "wenchang",
      pinyinShort: "wc",
      name: "文昌市",
      code: "469005",
      pcode: "460000",
    },
    {
      pinyin: "wenshanzhuangzumiaozuzizhizhou",
      pinyinShort: "wszzmzzzz",
      name: "文山壮族苗族自治州",
      code: "532600",
      pcode: "530000",
    },
    {
      pinyin: "wenzhou",
      pinyinShort: "wz",
      name: "温州市",
      code: "330300",
      pcode: "330000",
    },
    {
      pinyin: "wuhai",
      pinyinShort: "wh",
      name: "乌海市",
      code: "150300",
      pcode: "150000",
    },
    {
      pinyin: "wuhan",
      pinyinShort: "wh",
      name: "武汉市",
      code: "420100",
      pcode: "420000",
    },
    {
      pinyin: "wuhu",
      pinyinShort: "wh",
      name: "芜湖市",
      code: "340200",
      pcode: "340000",
    },
    {
      pinyin: "wujiaqu",
      pinyinShort: "wjq",
      name: "五家渠市",
      code: "659004",
      pcode: "650000",
    },
    {
      pinyin: "wulanchabu",
      pinyinShort: "wlcb",
      name: "乌兰察布市",
      code: "150900",
      pcode: "150000",
    },
    {
      pinyin: "wulumuqi",
      pinyinShort: "wlmq",
      name: "乌鲁木齐市",
      code: "650100",
      pcode: "650000",
    },
    {
      pinyin: "wuwei",
      pinyinShort: "ww",
      name: "武威市",
      code: "620600",
      pcode: "620000",
    },
    {
      pinyin: "wuxi",
      pinyinShort: "wx",
      name: "无锡市",
      code: "320200",
      pcode: "320000",
    },
    {
      pinyin: "wuzhishan",
      pinyinShort: "wzs",
      name: "五指山市",
      code: "469001",
      pcode: "460000",
    },
    {
      pinyin: "wuzhong",
      pinyinShort: "wz",
      name: "吴忠市",
      code: "640300",
      pcode: "640000",
    },
    {
      pinyin: "wuzhou",
      pinyinShort: "wz",
      name: "梧州市",
      code: "450400",
      pcode: "450000",
    },
  ],
  X: [
    {
      pinyin: "xiamen",
      pinyinShort: "xm",
      name: "厦门市",
      code: "350200",
      pcode: "350000",
    },
    {
      pinyin: "xian",
      pinyinShort: "xa",
      name: "西安市",
      code: "610100",
      pcode: "610000",
    },
    {
      pinyin: "xianggang",
      pinyinShort: "xg",
      name: "香港",
      code: "810000",
      pcode: "810000",
    },
    {
      pinyin: "xiangtan",
      pinyinShort: "xt",
      name: "湘潭市",
      code: "430300",
      pcode: "430000",
    },
    {
      pinyin: "xiangxitujiazumiaozuzizhizhou",
      pinyinShort: "xxtjzmzzzz",
      name: "湘西土家族苗族自治州",
      code: "433100",
      pcode: "430000",
    },
    {
      pinyin: "xiangyang",
      pinyinShort: "xy",
      name: "襄阳市",
      code: "420600",
      pcode: "420000",
    },
    {
      pinyin: "xianning",
      pinyinShort: "xn",
      name: "咸宁市",
      code: "421200",
      pcode: "420000",
    },
    {
      pinyin: "xiantao",
      pinyinShort: "xt",
      name: "仙桃市",
      code: "429004",
      pcode: "420000",
    },
    {
      pinyin: "xianyang",
      pinyinShort: "xy",
      name: "咸阳市",
      code: "610400",
      pcode: "610000",
    },
    {
      pinyin: "xiaogan",
      pinyinShort: "xg",
      name: "孝感市",
      code: "420900",
      pcode: "420000",
    },
    {
      pinyin: "xilinguolemeng",
      pinyinShort: "xlglm",
      name: "锡林郭勒盟",
      code: "152500",
      pcode: "150000",
    },
    {
      pinyin: "xinbei",
      pinyinShort: "xb",
      name: "新北市",
      code: "710300",
      pcode: "710000",
    },
    {
      pinyin: "xinganmeng",
      pinyinShort: "xam",
      name: "兴安盟",
      code: "152200",
      pcode: "150000",
    },
    {
      pinyin: "xingtai",
      pinyinShort: "xt",
      name: "邢台市",
      code: "130500",
      pcode: "130000",
    },
    {
      pinyin: "xining",
      pinyinShort: "xn",
      name: "西宁市",
      code: "630100",
      pcode: "630000",
    },
    {
      pinyin: "xinxiang",
      pinyinShort: "xx",
      name: "新乡市",
      code: "410700",
      pcode: "410000",
    },
    {
      pinyin: "xinxing",
      pinyinShort: "xx",
      name: "新星市",
      code: "659011",
      pcode: "650000",
    },
    {
      pinyin: "xinyang",
      pinyinShort: "xy",
      name: "信阳市",
      code: "411500",
      pcode: "410000",
    },
    {
      pinyin: "xinyu",
      pinyinShort: "xy",
      name: "新余市",
      code: "360500",
      pcode: "360000",
    },
    {
      pinyin: "xinzhou",
      pinyinShort: "xz",
      name: "忻州市",
      code: "140900",
      pcode: "140000",
    },
    {
      pinyin: "xinzhu",
      pinyinShort: "xz",
      name: "新竹市",
      code: "719002",
      pcode: "710000",
    },
    {
      pinyin: "xinzhuxian",
      pinyinShort: "xzx",
      name: "新竹县",
      code: "719004",
      pcode: "710000",
    },
    {
      pinyin: "xishuangbannadaizuzizhizhou",
      pinyinShort: "xsbndzzzz",
      name: "西双版纳傣族自治州",
      code: "532800",
      pcode: "530000",
    },
    {
      pinyin: "xuancheng",
      pinyinShort: "xc",
      name: "宣城市",
      code: "341800",
      pcode: "340000",
    },
    {
      pinyin: "xuchang",
      pinyinShort: "xc",
      name: "许昌市",
      code: "411000",
      pcode: "410000",
    },
    {
      pinyin: "xuzhou",
      pinyinShort: "xz",
      name: "徐州市",
      code: "320300",
      pcode: "320000",
    },
  ],
  Y: [
    {
      pinyin: "yaan",
      pinyinShort: "ya",
      name: "雅安市",
      code: "511800",
      pcode: "510000",
    },
    {
      pinyin: "yanan",
      pinyinShort: "ya",
      name: "延安市",
      code: "610600",
      pcode: "610000",
    },
    {
      pinyin: "yanbianchaoxianzuzizhizhou",
      pinyinShort: "ybcxzzzz",
      name: "延边朝鲜族自治州",
      code: "222400",
      pcode: "220000",
    },
    {
      pinyin: "yancheng",
      pinyinShort: "yc",
      name: "盐城市",
      code: "320900",
      pcode: "320000",
    },
    {
      pinyin: "yangjiang",
      pinyinShort: "yj",
      name: "阳江市",
      code: "441700",
      pcode: "440000",
    },
    {
      pinyin: "yangquan",
      pinyinShort: "yq",
      name: "阳泉市",
      code: "140300",
      pcode: "140000",
    },
    {
      pinyin: "yangzhou",
      pinyinShort: "yz",
      name: "扬州市",
      code: "321000",
      pcode: "320000",
    },
    {
      pinyin: "yantai",
      pinyinShort: "yt",
      name: "烟台市",
      code: "370600",
      pcode: "370000",
    },
    {
      pinyin: "yibin",
      pinyinShort: "yb",
      name: "宜宾市",
      code: "511500",
      pcode: "510000",
    },
    {
      pinyin: "yichang",
      pinyinShort: "yc",
      name: "宜昌市",
      code: "420500",
      pcode: "420000",
    },
    {
      pinyin: "yichun",
      pinyinShort: "yc",
      name: "宜春市",
      code: "360900",
      pcode: "360000",
    },
    {
      pinyin: "yichun",
      pinyinShort: "yc",
      name: "伊春市",
      code: "230700",
      pcode: "230000",
    },
    {
      pinyin: "yilanxian",
      pinyinShort: "ylx",
      name: "宜兰县",
      code: "719005",
      pcode: "710000",
    },
    {
      pinyin: "yilihasakezizhizhou",
      pinyinShort: "ylhskzzz",
      name: "伊犁哈萨克自治州",
      code: "654000",
      pcode: "650000",
    },
    {
      pinyin: "yinchuan",
      pinyinShort: "yc",
      name: "银川市",
      code: "640100",
      pcode: "640000",
    },
    {
      pinyin: "yingkou",
      pinyinShort: "yk",
      name: "营口市",
      code: "210800",
      pcode: "210000",
    },
    {
      pinyin: "yingtan",
      pinyinShort: "yt",
      name: "鹰潭市",
      code: "360600",
      pcode: "360000",
    },
    {
      pinyin: "yiyang",
      pinyinShort: "yy",
      name: "益阳市",
      code: "430900",
      pcode: "430000",
    },
    {
      pinyin: "yongzhou",
      pinyinShort: "yz",
      name: "永州市",
      code: "431100",
      pcode: "430000",
    },
    {
      pinyin: "yueyang",
      pinyinShort: "yy",
      name: "岳阳市",
      code: "430600",
      pcode: "430000",
    },
    {
      pinyin: "yulin",
      pinyinShort: "yl",
      name: "榆林市",
      code: "610800",
      pcode: "610000",
    },
    {
      pinyin: "yulin",
      pinyinShort: "yl",
      name: "玉林市",
      code: "450900",
      pcode: "450000",
    },
    {
      pinyin: "yuncheng",
      pinyinShort: "yc",
      name: "运城市",
      code: "140800",
      pcode: "140000",
    },
    {
      pinyin: "yunfu",
      pinyinShort: "yf",
      name: "云浮市",
      code: "445300",
      pcode: "440000",
    },
    {
      pinyin: "yunlinxian",
      pinyinShort: "ylx",
      name: "云林县",
      code: "719008",
      pcode: "710000",
    },
    {
      pinyin: "yushuzangzuzizhizhou",
      pinyinShort: "yszzzzz",
      name: "玉树藏族自治州",
      code: "632700",
      pcode: "630000",
    },
    {
      pinyin: "yuxi",
      pinyinShort: "yx",
      name: "玉溪市",
      code: "530400",
      pcode: "530000",
    },
  ],
  Z: [
    {
      pinyin: "zaozhuang",
      pinyinShort: "zz",
      name: "枣庄市",
      code: "370400",
      pcode: "370000",
    },
    {
      pinyin: "zhanghuaxian",
      pinyinShort: "zhx",
      name: "彰化县",
      code: "719007",
      pcode: "710000",
    },
    {
      pinyin: "zhangjiajie",
      pinyinShort: "zjj",
      name: "张家界市",
      code: "430800",
      pcode: "430000",
    },
    {
      pinyin: "zhangjiakou",
      pinyinShort: "zjk",
      name: "张家口市",
      code: "130700",
      pcode: "130000",
    },
    {
      pinyin: "zhangye",
      pinyinShort: "zy",
      name: "张掖市",
      code: "620700",
      pcode: "620000",
    },
    {
      pinyin: "zhangzhou",
      pinyinShort: "zz",
      name: "漳州市",
      code: "350600",
      pcode: "350000",
    },
    {
      pinyin: "zhanjiang",
      pinyinShort: "zj",
      name: "湛江市",
      code: "440800",
      pcode: "440000",
    },
    {
      pinyin: "zhaoqing",
      pinyinShort: "zq",
      name: "肇庆市",
      code: "441200",
      pcode: "440000",
    },
    {
      pinyin: "zhaotong",
      pinyinShort: "zt",
      name: "昭通市",
      code: "530600",
      pcode: "530000",
    },
    {
      pinyin: "zhengzhou",
      pinyinShort: "zz",
      name: "郑州市",
      code: "410100",
      pcode: "410000",
    },
    {
      pinyin: "zhenjiang",
      pinyinShort: "zj",
      name: "镇江市",
      code: "321100",
      pcode: "320000",
    },
    {
      pinyin: "zhongshan",
      pinyinShort: "zs",
      name: "中山市",
      code: "442000",
      pcode: "440000",
    },
    {
      pinyin: "zhongwei",
      pinyinShort: "zw",
      name: "中卫市",
      code: "640500",
      pcode: "640000",
    },
    {
      pinyin: "zhoukou",
      pinyinShort: "zk",
      name: "周口市",
      code: "411600",
      pcode: "410000",
    },
    {
      pinyin: "zhoushan",
      pinyinShort: "zs",
      name: "舟山市",
      code: "330900",
      pcode: "330000",
    },
    {
      pinyin: "zhuhai",
      pinyinShort: "zh",
      name: "珠海市",
      code: "440400",
      pcode: "440000",
    },
    {
      pinyin: "zhumadian",
      pinyinShort: "zmd",
      name: "驻马店市",
      code: "411700",
      pcode: "410000",
    },
    {
      pinyin: "zhuzhou",
      pinyinShort: "zz",
      name: "株洲市",
      code: "430200",
      pcode: "430000",
    },
    {
      pinyin: "zibo",
      pinyinShort: "zb",
      name: "淄博市",
      code: "370300",
      pcode: "370000",
    },
    {
      pinyin: "zigong",
      pinyinShort: "zg",
      name: "自贡市",
      code: "510300",
      pcode: "510000",
    },
    {
      pinyin: "ziyang",
      pinyinShort: "zy",
      name: "资阳市",
      code: "512000",
      pcode: "510000",
    },
    {
      pinyin: "zunyi",
      pinyinShort: "zy",
      name: "遵义市",
      code: "520300",
      pcode: "520000",
    },
  ],
};
