"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = require("@emotion/core");
var cssUtil_1 = require("../cssUtil");
exports.showAnimation = core_1.keyframes(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\nfrom {\n  opacity: 0;\n  transform: scale(0.9);\n}\nto {\n  opacity: 1;\n  transform: scale(1);\n}\n"], ["\nfrom {\n  opacity: 0;\n  transform: scale(0.9);\n}\nto {\n  opacity: 1;\n  transform: scale(1);\n}\n"])));
exports.hideAnimation = core_1.keyframes(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\nfrom {\n  opacity: 1;\n  transform: scale(1);\n}\nto {\n  opacity: 0;\n  transform: scale(0.9);\n}\n"], ["\nfrom {\n  opacity: 1;\n  transform: scale(1);\n}\nto {\n  opacity: 0;\n  transform: scale(0.9);\n}\n"])));
exports.style = {
    alert: core_1.css(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    position: fixed;\n    top: 0;\n    left: 0;\n    width: 100%;\n    height: 100%;\n    display: flex;\n    justify-content: center;\n    align-items: center;\n  "], ["\n    position: fixed;\n    top: 0;\n    left: 0;\n    width: 100%;\n    height: 100%;\n    display: flex;\n    justify-content: center;\n    align-items: center;\n  "]))),
    alertMask: core_1.css(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    background-color: rgba(0, 0, 0, 0.5);\n  "], ["\n    background-color: rgba(0, 0, 0, 0.5);\n  "]))),
    container: core_1.css(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n    background-color: #fff;\n    width: ", ";\n    border-radius: ", ";\n    overflow: hidden;\n    box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.2);\n    @media screen and (min-width: 576px) {\n      width: 300px;\n      border-radius: 10px;\n    }\n  "], ["\n    background-color: #fff;\n    width: ", ";\n    border-radius: ", ";\n    overflow: hidden;\n    box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.2);\n    @media screen and (min-width: 576px) {\n      width: 300px;\n      border-radius: 10px;\n    }\n  "])), cssUtil_1.vw(250), cssUtil_1.vw(10)),
    containerShow: core_1.css(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n    animation: ", " 100ms ease-in;\n  "], ["\n    animation: ", " 100ms ease-in;\n  "])), exports.showAnimation),
    containerHide: core_1.css(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n    animation: ", " 100ms ease-out;\n  "], ["\n    animation: ", " 100ms ease-out;\n  "])), exports.hideAnimation),
    content: core_1.css(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n    font-size: ", ";\n    margin: 0;\n    padding: ", ";\n    text-align: center;\n    color: #333;\n    line-height: 1.6;\n    @media screen and (min-width: 576px) {\n      font-size: 16px;\n      padding: 30px;\n    }\n  "], ["\n    font-size: ", ";\n    margin: 0;\n    padding: ", ";\n    text-align: center;\n    color: #333;\n    line-height: 1.6;\n    @media screen and (min-width: 576px) {\n      font-size: 16px;\n      padding: 30px;\n    }\n  "])), cssUtil_1.vw(16), cssUtil_1.vw(20)),
    btn: core_1.css(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n    display: flex;\n    border-top: 1px solid #f0f0f0;\n    font-size: 0;\n    div {\n      cursor: pointer;\n      flex: 1;\n      background: transparent;\n      font-size: ", ";\n      line-height: ", ";\n      text-align: center;\n      box-sizing: border-box;\n      user-select: none;\n      -webkit-tap-highlight-color: transparent;\n      font-weight: 500;\n      @media screen and (min-width: 576px) {\n        font-size: 15px;\n        line-height: 50px;\n      }\n    }\n  "], ["\n    display: flex;\n    border-top: 1px solid #f0f0f0;\n    font-size: 0;\n    div {\n      cursor: pointer;\n      flex: 1;\n      background: transparent;\n      font-size: ", ";\n      line-height: ", ";\n      text-align: center;\n      box-sizing: border-box;\n      user-select: none;\n      -webkit-tap-highlight-color: transparent;\n      font-weight: 500;\n      @media screen and (min-width: 576px) {\n        font-size: 15px;\n        line-height: 50px;\n      }\n    }\n  "])), cssUtil_1.vw(15), cssUtil_1.vw(44)),
    confirm: core_1.css(templateObject_10 || (templateObject_10 = __makeTemplateObject(["\n    border: none;\n    color: #007bff;\n    &:active {\n      color: #007bff - #333;\n      background-color: #f5f5f5;\n    }\n  "], ["\n    border: none;\n    color: #007bff;\n    &:active {\n      color: #007bff - #333;\n      background-color: #f5f5f5;\n    }\n  "]))),
    cancel: core_1.css(templateObject_11 || (templateObject_11 = __makeTemplateObject(["\n    border: none;\n    border-right: 1px solid #f0f0f0;\n    color: #888;\n    &:active {\n      color: #555;\n      background-color: #f5f5f5;\n    }\n  "], ["\n    border: none;\n    border-right: 1px solid #f0f0f0;\n    color: #888;\n    &:active {\n      color: #555;\n      background-color: #f5f5f5;\n    }\n  "])))
};
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10, templateObject_11;
